version: "3.9"

services:
  app:
    container_name: amazhist
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/amazhist/data
      - ./output:/opt/amazhist/output
