name: Build executable
on:
    push:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/amazhist.py
          include-package: |
            enlighten
            selenium.webdriver.support
            PIL.Image
            openpyxl
            logging.handlers
            coloredlogs
            yaml
          onefile: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
